services:
  lavalink:
    image: "ghcr.io/lavalink-devs/lavalink:latest" # Use the latest version of Lavalink
    container_name: "lavalink"
    restart: "unless-stopped"
    volumes:
      - "./lavalink/application.yml:/opt/Lavalink/application.yml"
      - "./lavalink/plugins/youtube-plugin-1.13.5.jar:/opt/Lavalink/plugins/youtube-plugin-1.13.5.jar"
      - "./lavalink/plugins/lavasrc-plugin-4.8.1.jar:/opt/Lavalink/plugins/lavasrc-plugin-4.8.1.jar"
      - "./lavalink/plugins/lavalyrics-plugin-1.0.0.jar:/opt/Lavalink/plugins/lavalyrics-plugin-1.0.0.jar"
    networks:
      - lavalink
    expose:
      - "2333"
    ports:
      - "2333:2333"
networks:
  lavalink:
    driver: bridge