services:
  lavalink:
    image: "ghcr.io/lavalink-devs/lavalink:4.1.2" # Use the latest version of Lavalink
    container_name: "lavalink"
    network_mode: "host"
    volumes:
      - "./lavalink/application.yml:/opt/Lavalink/application.yml"
    #networks:
    #  - lavalink
    expose:
      - "2333"
    ports:
      - "2333:2333"
    restart: "unless-stopped"